const companiesData = [
  {
    id: 1,
    name: 'Urban Ventures Ltd.',
    email: 'contact@urbanventures.com',
    industry: 'Real Estate',
    location: 'Chicago, IL',
    website: 'https://www.urbanventures.com',
    phone: '+1 (312) 345-6789',
    employees: 80,
    registeredAt: '2020-11-10',
    active: true,
    companyType: 'LLC',
    taxIdentificationNumber: '123-45-6789',
    annualRevenue: '$5,000,000',
    socialMedia: {
      linkedin: 'https://www.linkedin.com/company/urbanventures',
      twitter: 'https://twitter.com/urbanventures',
      facebook: 'https://facebook.com/urbanventures',
    },
    ceoName: 'John Doe',
    numberOfLocations: 5,
    businessHours: 'Mon-Fri 9:00 AM - 6:00 PM',
    primaryProductService: 'Residential and Commercial Real Estate Development',
    companyLogoURL: 'https://www.urbanventures.com/logo.png',
    customerSupportEmail: 'support@urbanventures.com',
    dateOfLastUpdate: '2025-04-11',
  },

  {
    id: 2,
    name: 'TechX Innovations Inc.',
    email: 'contact@techx.com',
    industry: 'Technology',
    location: 'San Francisco, CA',
    website: 'https://www.techx.com',
    phone: '+1 (415) 123-4567',
    employees: 250,
    registeredAt: '2012-03-05',
    active: true,
    companyType: 'C Corporation',
    taxIdentificationNumber: '987-65-4321',
    annualRevenue: '$50,000,000',
    socialMedia: {
      linkedin: 'https://www.linkedin.com/company/techx',
      twitter: 'https://twitter.com/techx',
      facebook: 'https://facebook.com/techx',
    },
    ceoName: 'Alice Smith',
    numberOfLocations: 10,
    businessHours: 'Mon-Fri 8:00 AM - 5:00 PM',
    primaryProductService: 'Cloud Services and AI Solutions',
    companyLogoURL: 'https://www.techx.com/logo.png',
    customerSupportEmail: 'support@techx.com',
    dateOfLastUpdate: '2025-04-11',
  },
  {
    id: 3,
    name: 'Global Foods Ltd.',
    email: 'contact@globalfoods.com',
    industry: 'Food & Beverage',
    location: 'New York, NY',
    website: 'https://www.globalfoods.com',
    phone: '+1 (212) 234-5678',
    employees: 500,
    registeredAt: '2005-06-12',
    active: true,
    companyType: 'Private Limited',
    taxIdentificationNumber: '456-78-1234',
    annualRevenue: '$30,000,000',
    socialMedia: {
      linkedin: 'https://www.linkedin.com/company/globalfoods',
      twitter: 'https://twitter.com/globalfoods',
      facebook: 'https://facebook.com/globalfoods',
    },
    ceoName: 'Bob Johnson',
    numberOfLocations: 15,
    businessHours: 'Mon-Sun 7:00 AM - 10:00 PM',
    primaryProductService: 'Packaged Food and Beverages',
    companyLogoURL: 'https://www.globalfoods.com/logo.png',
    customerSupportEmail: 'support@globalfoods.com',
    dateOfLastUpdate: '2025-04-11',
  },
  {
    id: 4,
    name: 'GreenTech Solutions',
    email: 'contact@greentech.com',
    industry: 'Environmental Technology',
    location: 'Los Angeles, CA',
    website: 'https://www.greentech.com',
    phone: '+1 (323) 987-6543',
    employees: 120,
    registeredAt: '2010-04-20',
    active: true,
    companyType: 'B Corporation',
    taxIdentificationNumber: '112-34-5678',
    annualRevenue: '$15,000,000',
    socialMedia: {
      linkedin: 'https://www.linkedin.com/company/greentech',
      twitter: 'https://twitter.com/greentech',
      facebook: 'https://facebook.com/greentech',
    },
    ceoName: 'Samantha Green',
    numberOfLocations: 8,
    businessHours: 'Mon-Fri 9:00 AM - 5:00 PM',
    primaryProductService: 'Renewable Energy Solutions',
    companyLogoURL: 'https://www.greentech.com/logo.png',
    customerSupportEmail: 'support@greentech.com',
    dateOfLastUpdate: '2025-04-11',
  },
  {
    id: 5,
    name: 'Medicare Innovations',
    email: 'contact@medicareinnovations.com',
    industry: 'Healthcare',
    location: 'Miami, FL',
    website: 'https://www.medicareinnovations.com',
    phone: '+1 (305) 654-9876',
    employees: 350,
    registeredAt: '2015-09-01',
    active: true,
    companyType: 'Public Corporation',
    taxIdentificationNumber: '321-54-9876',
    annualRevenue: '$80,000,000',
    socialMedia: {
      linkedin: 'https://www.linkedin.com/company/medicareinnovations',
      twitter: 'https://twitter.com/medicareinnovations',
      facebook: 'https://facebook.com/medicareinnovations',
    },
    ceoName: 'Dr. Michael White',
    numberOfLocations: 20,
    businessHours: 'Mon-Fri 8:00 AM - 6:00 PM',
    primaryProductService: 'Healthcare Solutions and Medical Devices',
    companyLogoURL: 'https://www.medicareinnovations.com/logo.png',
    customerSupportEmail: 'support@medicareinnovations.com',
    dateOfLastUpdate: '2025-04-11',
  },
  {
    id: 6,
    name: 'AutoX Motors',
    email: 'contact@autoxmotors.com',
    industry: 'Automotive',
    location: 'Detroit, MI',
    website: 'https://www.autoxmotors.com',
    phone: '+1 (313) 890-1234',
    employees: 1000,
    registeredAt: '1998-07-14',
    active: true,
    companyType: 'S Corporation',
    taxIdentificationNumber: '567-89-0123',
    annualRevenue: '$200,000,000',
    socialMedia: {
      linkedin: 'https://www.linkedin.com/company/autoxmotors',
      twitter: 'https://twitter.com/autoxmotors',
      facebook: 'https://facebook.com/autoxmotors',
    },
    ceoName: 'James Taylor',
    numberOfLocations: 25,
    businessHours: 'Mon-Sat 8:00 AM - 7:00 PM',
    primaryProductService: 'Electric Vehicles and Automotive Parts',
    companyLogoURL: 'https://www.autoxmotors.com/logo.png',
    customerSupportEmail: 'support@autoxmotors.com',
    dateOfLastUpdate: '2025-04-11',
  },
]
