export const JobData = [
  {
    id: 1,
    title: 'Frontend Developer',
    company: 'PixelCraft Studio',
    location: 'Remote',
    type: 'full-time',
    category: 'development',
    level: 'mid',
    description:
      'As a Frontend Developer at PixelCraft, you’ll build responsive, accessible UIs with React and Tailwind CSS. You’ll collaborate with designers to implement pixel-perfect layouts, optimize performance, and ensure cross-browser compatibility. Responsibilities include writing reusable components, integrating APIs, and participating in code reviews. Ideal candidates have 3+ years of experience with modern JavaScript, state management (Redux/Zustand), and testing frameworks.',
    postedAt: '2025-04-08',
    countryFlag: null,
  },
  {
    id: 2,
    title: 'UI/UX Designer',
    company: 'DesignHub',
    location: 'Lagos, Nigeria',
    type: 'contract',
    category: 'design',
    level: 'entry',
    description:
      'DesignHub seeks a UI/UX Designer to create intuitive digital experiences. You’ll conduct user research, design wireframes/prototypes (Figma/Adobe XD), and collaborate with developers. Responsibilities include usability testing, maintaining design systems, and ensuring ADA compliance. Perfect for graduates with a design portfolio showcasing UX thinking. Bonus: Motion design or frontend basics (HTML/CSS).',
    postedAt: '2025-04-09',
    countryFlag: 'ng',
  },
  {
    id: 3,
    title: 'Digital Marketer',
    company: 'Marketly',
    location: 'Remote',
    type: 'part-time',
    category: 'marketing',
    level: 'mid',
    description:
      'Marketly needs a Digital Marketer to lead campaigns across Google Ads, Meta, and LinkedIn. You’ll analyze KPIs, A/B test creatives, and optimize ROAS. Requires 2+ years managing $50k+ monthly ad spend, Google Analytics certification, and experience with CRM tools. Remote role with flexible hours—ideal for performance-driven marketers.',
    postedAt: '2025-04-05',
    countryFlag: null,
  },
  {
    id: 4,
    title: 'Product Manager',
    company: 'VisionSoft',
    location: 'Nairobi, Kenya',
    type: 'full-time',
    category: 'product-management',
    level: 'senior',
    description:
      'VisionSoft seeks a Senior Product Manager to drive our SaaS platform’s roadmap. You’ll gather requirements, prioritize features (Jira), and lead agile ceremonies. Requires 5+ years in B2B tech, proven success with MVP launches, and strong SQL/data analysis skills. Must excel at stakeholder management across engineering, sales, and C-suite.',
    postedAt: '2025-04-06',
    countryFlag: 'ke',
  },
  {
    id: 5,
    title: 'Customer Support Agent',
    company: 'Helpify',
    location: 'Remote',
    type: 'remote',
    category: 'support',
    level: 'entry',
    description:
      'Join Helpify as the first point of contact for customers. You’ll troubleshoot via chat/email (Zendesk), document solutions, and escalate technical issues. Requires flawless English, patience with non-tech users, and availability for rotating shifts. Growth path to Tier 2 support or QA roles. Full training provided—no prior experience needed.',
    postedAt: '2025-04-04',
    countryFlag: null,
  },
  {
    id: 6,
    title: 'Backend Developer',
    company: 'TechWave',
    location: 'Cape Town, South Africa',
    type: 'full-time',
    category: 'development',
    level: 'senior',
    description:
      'TechWave needs a Senior Backend Developer to architect scalable APIs with Node.js/Express. You’ll optimize PostgreSQL queries, implement CI/CD pipelines, and mentor juniors. Requires 5+ years building microservices, AWS/GCP expertise, and OAuth security knowledge. Bonus: Open-source contributions or Kubernetes experience.',
    postedAt: '2025-04-07',
    countryFlag: 'za',
  },
  {
    id: 7,
    title: 'Graphic Designer',
    company: 'ArtWorks Co.',
    location: 'Remote',
    type: 'freelance',
    category: 'design',
    level: 'mid',
    description:
      'ArtWorks seeks a freelance Graphic Designer for branding projects. You’ll create logos, social media assets (Canva/Photoshop), and print materials. Ideal candidates have 3+ years agency experience, strong typography skills, and the ability to adapt to brand guidelines. Remote work with flexible deadlines—portfolio required.',
    postedAt: '2025-04-03',
    countryFlag: null,
  },
  {
    id: 8,
    title: 'Data Analyst',
    company: 'DataScience Inc.',
    location: 'London, UK',
    type: 'part-time',
    category: 'data',
    level: 'mid',
    description:
      'DataScience Inc. needs a part-time Data Analyst to transform raw data into actionable insights. You’ll build dashboards (Tableau/Power BI), write SQL queries, and present findings to stakeholders. Requires 2+ years with Python/R, statistical analysis skills, and familiarity with ETL processes. Hybrid role (2 days/week in office).',
    postedAt: '2025-04-02',
    countryFlag: 'gb',
  },
  {
    id: 9,
    title: 'Content Writer',
    company: 'ContentHub',
    location: 'Remote',
    type: 'full-time',
    category: 'marketing',
    level: 'entry',
    description:
      'ContentHub seeks a writer to produce SEO-optimized blogs, whitepapers, and case studies. You’ll research trending tech topics (AI, blockchain), maintain an editorial calendar, and collaborate with designers. Requires native English, 1+ year writing samples, and basic WordPress knowledge. Growth into content strategy possible.',
    postedAt: '2025-04-01',
    countryFlag: null,
  },
  {
    id: 10,
    title: 'DevOps Engineer',
    company: 'Cloudify',
    location: 'Remote',
    type: 'full-time',
    category: 'development',
    level: 'senior',
    description:
      'Cloudify needs a DevOps Engineer to automate AWS/GCP infrastructure (Terraform), manage Kubernetes clusters, and implement monitoring (Prometheus/Grafana). Requires 5+ years with CI/CD (GitHub Actions/Jenkins), Linux administration, and incident response. Must have security-first mindset (SOC2 compliance experience preferred).',
    postedAt: '2025-03-30',
    countryFlag: null,
  },
  {
    id: 11,
    title: 'SEO Specialist',
    company: 'SEO Masters',
    location: 'Berlin, Germany',
    type: 'contract',
    category: 'marketing',
    level: 'mid',
    description:
      'SEO Masters seeks a contractor to audit websites, conduct keyword research (Ahrefs/SEMrush), and optimize technical SEO. You’ll collaborate with content teams to improve rankings and track progress via Google Search Console. Requires 3+ years increasing organic traffic, multilingual SEO experience (German/English), and CMS expertise.',
    postedAt: '2025-03-29',
    countryFlag: 'de',
  },
  {
    id: 12,
    title: 'HR Manager',
    company: 'PeopleFirst',
    location: 'Accra, Ghana',
    type: 'full-time',
    category: 'human-resources',
    level: 'senior',
    description:
      'PeopleFirst needs an HR Manager to oversee 100+ employees. You’ll lead recruitment, design L&D programs, and ensure compliance with Ghanaian labor laws. Requires 7+ years HR experience, CIPD certification, and expertise in HRIS (BambooHR/Sage). Must excel at conflict resolution and employer branding initiatives.',
    postedAt: '2025-03-28',
    countryFlag: 'gh',
  },
  {
    id: 13,
    title: 'Mobile Developer',
    company: 'AppX',
    location: 'Remote',
    type: 'full-time',
    category: 'development',
    level: 'mid',
    description:
      'AppX seeks a Mobile Developer to build cross-platform apps with React Native/Flutter. You’ll integrate Firebase, implement animations, and publish to stores. Requires 3+ years shipping apps, state management (Bloc/Provider), and offline-first design experience. Bonus: GraphQL or Swift/Kotlin knowledge.',
    postedAt: '2025-03-27',
    countryFlag: null,
  },
  {
    id: 14,
    title: 'Sales Manager',
    company: 'SalesPro',
    location: 'Singapore',
    type: 'full-time',
    category: 'sales',
    level: 'senior',
    description:
      'SalesPro seeks a Senior Sales Manager to lead APAC expansion. You’ll close enterprise deals ($100k+ ARR), coach a team of 5, and refine sales playbooks. Requires 8+ years in SaaS sales, CRM expertise (HubSpot/Salesforce), and proven quota attainment. Fluency in Mandarin is a plus for regional clients.',
    postedAt: '2025-03-26',
    countryFlag: 'sg',
  },
  {
    id: 15,
    title: 'Business Analyst',
    company: 'BizSolutions',
    location: 'Remote',
    type: 'full-time',
    category: 'business',
    level: 'mid',
    description:
      'BizSolutions needs a Business Analyst to document processes, model data flows (Lucidchart), and recommend improvements. You’ll create user stories, facilitate workshops, and track KPIs. Requires 4+ years with Agile methodologies, BPMN knowledge, and experience in fintech/healthcare domains.',
    postedAt: '2025-03-25',
    countryFlag: null,
  },
  {
    id: 16,
    title: 'Customer Success Manager',
    company: 'CustomerFirst',
    location: 'New York, USA',
    type: 'remote',
    category: 'support',
    level: 'mid',
    description:
      'CustomerFirst seeks a CSM to onboard clients, drive adoption (Gainsight), and reduce churn. You’ll analyze usage data, conduct QBRs, and advocate for product enhancements. Requires 3+ years managing B2B accounts, technical aptitude (APIs/SFTP), and exceptional presentation skills. Remote with occasional NYC travel.',
    postedAt: '2025-03-24',
    countryFlag: 'us',
  },
  {
    id: 17,
    title: 'Web Designer',
    company: 'DesignCraft',
    location: 'London, UK',
    type: 'freelance',
    category: 'design',
    level: 'entry',
    description:
      'DesignCraft needs a freelance Web Designer to create responsive sites (HTML/CSS/JS) from Figma mockups. You’ll ensure WCAG compliance, optimize for Core Web Vitals, and collaborate with WordPress developers. Ideal for graduates with 1-2 personal projects. Mentorship provided—portfolio required.',
    postedAt: '2025-03-23',
    countryFlag: 'gb',
  },
  {
    id: 18,
    title: 'Chief Technology Officer (CTO)',
    company: 'Tech Innovators',
    location: 'Remote',
    type: 'full-time',
    category: 'development',
    level: 'executive',
    description:
      'Tech Innovators seeks a CTO to define our tech vision. You’ll architect scalable systems, lead 20+ engineers, and evaluate emerging tech (AI/blockchain). Requires 10+ years engineering leadership, fundraising experience (Series A+), and expertise in Go/Rust. Must balance innovation with pragmatic delivery timelines.',
    postedAt: '2025-03-22',
    countryFlag: null,
  },
  {
    id: 19,
    title: 'Marketing Specialist',
    company: 'MarketReach',
    location: 'Johannesburg, South Africa',
    type: 'part-time',
    category: 'marketing',
    level: 'entry',
    description:
      'MarketReach needs a Marketing Specialist to execute campaigns across email, social, and events. You’ll analyze metrics (Google Analytics), coordinate with influencers, and assist with PR. Ideal for marketing graduates proficient in Canva/Mailchimp. Hybrid role (3 days/week) with potential for full-time conversion.',
    postedAt: '2025-03-21',
    countryFlag: 'za',
  },
  {
    id: 20,
    title: 'UX Researcher',
    company: 'UX Insights',
    location: 'Remote',
    type: 'contract',
    category: 'design',
    level: 'mid',
    description:
      'UX Insights seeks a researcher to conduct user interviews, surveys, and usability tests. You’ll synthesize findings into personas/journey maps and present to product teams. Requires 3+ years research experience, Mixpanel/Hotjar proficiency, and psychology/sociology background. 6-month contract with possible extension.',
    postedAt: '2025-03-20',
    countryFlag: null,
  },
  {
    id: 21,
    title: 'Social Media Manager',
    company: 'Socialify',
    location: 'Cape Town, South Africa',
    type: 'freelance',
    category: 'marketing',
    level: 'mid',
    description:
      'Socialify needs a freelance Social Media Manager to grow our clients’ presence. You’ll create TikTok/Instagram content calendars, engage communities, and report on KPIs. Requires 2+ years managing brand accounts, video editing skills (CapCut/Premiere), and trend-spotting ability. Portfolio of viral posts preferred.',
    postedAt: '2025-03-19',
    countryFlag: 'za',
  },
  {
    id: 22,
    title: 'JavaScript Developer',
    company: 'DevSolutions',
    location: 'Berlin, Germany',
    type: 'full-time',
    category: 'development',
    level: 'mid',
    description:
      'DevSolutions seeks a JavaScript Developer to build interactive web apps with React/Next.js. You’ll optimize SSR performance, write unit tests (Jest), and contribute to open-source libraries. Requires 3+ years with TypeScript, GraphQL, and modular CSS. Visa sponsorship available for qualified candidates.',
    postedAt: '2025-03-18',
    countryFlag: 'de',
  },
  {
    id: 23,
    title: 'Graphic Designer (3D)',
    company: 'CreativeWorks',
    location: 'Lagos, Nigeria',
    type: 'contract',
    category: 'design',
    level: 'mid',
    description:
      'CreativeWorks needs a 3D Designer for product visualizations (Blender/Maya). You’ll create photorealistic renders, animations, and AR-ready assets. Requires 2+ years in e-commerce/product design, UV mapping expertise, and portfolio showcasing lighting/texturing skills. 3-month contract with potential for renewal.',
    postedAt: '2025-03-17',
    countryFlag: 'ng',
  },
]
